name: for_aveds
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

  #UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter

  #SIGN IN
  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/svg/
    - assets/images/png/
flutter_intl:
  enabled: true
